namespace: aistor

resources:
  - ../base

patches:
  - path: overlay/aistor-statefulset.yaml
    target:
      group: apps
      kind: StatefulSet
      name: aistor
      namespace: aistor
      version: v1
  - path: overlay/aistor-service.yaml
    target:
      kind: Service
      name: aistor
      namespace: aistor
      version: v1
  - path: overlay/aistor-service-hl.yaml
    target:
      kind: Service
      name: aistor-hl
      namespace: aistor
      version: v1
