apiVersion: v1
kind: Service
metadata:
  name: eos-controller-hl
  namespace: eos
  labels:
    eos.min.io/name: eos
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8444
    - name: control-plane
      protocol: TCP
      port: 7899
  selector:
    eos.min.io/name: eos-controller
