apiVersion: v1
kind: Service
metadata:
  name: eos-controller
  namespace: eos
  labels:
    eos.min.io/name: eos
spec:
  ports:
    - name: http
      port: 8444
    - name: control-plane
      protocol: TCP
      port: 7899
  selector:
    eos.min.io/name: eos-controller
