apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opr-migration-job-ns-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-delete-ns-role
subjects:
  - kind: ServiceAccount
    name: aistor-migration-job
    namespace: aistor
