apiVersion: v1
kind: Service
metadata:
  name: object-store-operator
  labels:
    aistor.min.io/name: object-store-operator
  namespace: aistor
spec:
  type: ClusterIP
  ports:
    - port: 4221
      name: http
  selector:
    aistor.min.io/name: object-store-operator
    operator: leader
---
apiVersion: v1
kind: Service
metadata:
  name: sts # Please do not change this value
  namespace: aistor
  annotations:
    aistor.min.io/app: sts
spec:
  type: ClusterIP
  ports:
    - port: 4223
      targetPort: 4223
      name: https
  selector:
    aistor.min.io/name: object-store-operator
