apiVersion: v1
kind: Service
metadata:
  name: eos
  namespace: aistor
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: aistor-tls
spec:
  ports:
    - name: https
      protocol: TCP
      port: 9443
  selector:
    aistor.min.io/name: aistor
