apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aistor
  namespace: aistor
  labels:
    aistor.min.io/name: aistor
spec:
  template:
    spec:
      securityContext: null
      containers:
        - name: console
          securityContext: null
          args:
            - server
            - --tls-ca
            - /.aistor/certs/CAs
          volumeMounts:
            - name: tls-certificates
              mountPath: /.aistor/certs
      volumes:
        - name: tls-certificates
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: openshift-service-ca.crt
                  items:
                    - key: service-ca.crt
                      path: CAs/openshift-service-ca.crt
                  optional: true
              - secret:
                  name: openshift-csr-signer-ca
                  items:
                    - key: tls.crt
                      path: CAs/openshift-csr-signer-ca.crt
                  optional: true
